owner: devbeacon-io
repo: status

sites:
  - name: Website
    url: https://devbeacon.io
  - name: App
    url: https://app.devbeacon.io
  - name: Docs
    url: https://docs.devbeacon.io
  - name: API
    url: https://api.devbeacon.io

status-website:
  cname: status.devbeacon.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Beacon Status
  introTitle: ''
  introMessage: ''
  navbar:
    - title: Return to Site
      href: https://devbeacon.io/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

